#!/usr/bin/env node
// registry-app/scripts/build-globals.mjs
//
// Regenerates registry-app/app/globals.css — the single Tailwind v4 + shadcn
// theme stylesheet shipped by the @hbd/hbd-theme registry item. Run this after
// changing tokens (../tokens/tokens.json -> tokens.css), the themes, or any
// de-shadowed component CSS under registry/new-york/styles/components/.
//
//   node scripts/build-globals.mjs
//
// Self-contained: reads the token CSS + themes from ./tokens, the Tailwind
// @theme inline block from ./scripts/theme-inline.css, and folds every component
// stylesheet into one file (Vite/Next-safe single import). No external deps.

import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve, join } from "node:path";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REG = resolve(SCRIPT_DIR, ".."); // project root (the registry app)
const read = (p) => readFileSync(p, "utf8").trim();

const tokens = read(`${REG}/tokens/tokens.css`);
const light = read(`${REG}/tokens/themes/light.css`);
const dark = read(`${REG}/tokens/themes/dark.css`);
const hc = read(`${REG}/tokens/themes/high-contrast.css`);
const themeBlock = read(`${SCRIPT_DIR}/theme-inline.css`);

const header = `/* Here Be Dragons DS — registry-app/app/globals.css  (GENERATED by scripts/build-globals.mjs — do not edit by hand)
 * Tailwind v4 + shadcn theme. 1:1 reproduction of the HBD token system.
 * Composition: imports -> @custom-variant dark -> @font-face -> the full token
 * system (verbatim from tokens/tokens.css) -> theme overrides (themes/*.css) ->
 * shadcn semantic aliases -> @theme inline utilities -> @layer base -> every
 * de-shadowed component stylesheet (folded in so one import loads all styles).
 */

/* Google Fonts MUST be the first @import: Tailwind v4 expands \`@import "tailwindcss"\`
 * in place, so any @import after it violates the CSS "@import first" rule
 * (a fatal parse error under Turbopack / Lightning CSS). */
@import url('https://fonts.googleapis.com/css2?family=Cinzel:wght@400;600;700;900&family=IM+Fell+English:ital@0;1&family=JetBrains+Mono:wght@400;500&family=Roboto:ital,wght@0,300;0,400;0,500;0,700;1,400&display=swap');
@import "tailwindcss";
@import "tw-animate-css";

@custom-variant dark (&:where(.dark, [data-theme="dark"], [data-theme="dark"] *));

@font-face {
  font-family: 'Tiamat Condensed SC';
  src: url('/fonts/assets_TiamatCondensedSC-Regular.woff2') format('woff2'),
       url('/fonts/assets_TiamatCondensedSC-Regular.woff') format('woff'),
       url('/fonts/assets_TiamatCondensedSC-Regular.ttf') format('truetype');
  font-weight: 400 700;
  font-style: normal;
  font-display: swap;
}`;

const aliases = `/* shadcn semantic aliases -> HBD semantic tokens (cascade through [data-theme] automatically) */
:root {
  --background: var(--hbd-color-surface-default);
  --foreground: var(--hbd-color-text-primary);
  --card: var(--hbd-color-surface-default);
  --card-foreground: var(--hbd-color-text-primary);
  --popover: var(--hbd-color-surface-raised);
  --popover-foreground: var(--hbd-color-text-primary);
  --primary: var(--hbd-color-surface-action);
  --primary-foreground: var(--hbd-color-text-on-action);
  --secondary: var(--hbd-color-surface-subtle);
  --secondary-foreground: var(--hbd-color-text-primary);
  --muted: var(--hbd-color-surface-muted);
  --muted-foreground: var(--hbd-color-text-muted);
  --accent: var(--hbd-color-surface-raised);
  --accent-foreground: var(--hbd-color-text-primary);
  --destructive: var(--hbd-color-status-error-surface);
  --destructive-foreground: var(--hbd-color-status-error-text);
  --border: var(--hbd-color-border-default);
  --input: var(--hbd-color-border-default);
  --ring: var(--hbd-color-focus-ring);
  --radius: var(--hbd-radius-lg);
}`;

const shadowBump = `/* Dark-mode elevation: deepen the offset shadows (elevation behaviour, not colour) */
.dark,
[data-theme="dark"] {
  --hbd-shadow-sm: 0 1px 2px rgba(26, 20, 16, 0.40);
  --hbd-shadow-md: 0 2px 6px rgba(26, 20, 16, 0.50), 0 1px 2px rgba(26, 20, 16, 0.35);
  --hbd-shadow-lg: 0 4px 12px rgba(26, 20, 16, 0.55), 0 2px 4px rgba(26, 20, 16, 0.40);
  --hbd-shadow-xl: 0 8px 24px rgba(26, 20, 16, 0.60), 0 4px 8px rgba(26, 20, 16, 0.45);
  --hbd-shadow-inner: inset 0 1px 3px rgba(26, 20, 16, 0.60);
}`;

const base = `@layer base {
  * { border-color: var(--hbd-color-border-default); }
  body {
    background-color: var(--hbd-color-surface-default);
    color: var(--hbd-color-text-primary);
    font-family: var(--hbd-font-family-serif);
    font-size: var(--hbd-font-size-body);
    line-height: var(--hbd-line-height-body);
    -webkit-font-smoothing: antialiased;
  }
  h1 { font-family: var(--hbd-font-family-accent);  font-size: var(--hbd-font-size-h1); letter-spacing: var(--hbd-letter-spacing-display); line-height: var(--hbd-line-height-display); }
  h2 { font-family: var(--hbd-font-family-display); font-size: var(--hbd-font-size-h2); font-weight: var(--hbd-font-weight-bold); letter-spacing: var(--hbd-letter-spacing-display); line-height: var(--hbd-line-height-display); }
  h3 { font-family: var(--hbd-font-family-accent);  font-size: var(--hbd-font-size-h3); letter-spacing: var(--hbd-letter-spacing-display); line-height: var(--hbd-line-height-display); }
  h4 { font-family: var(--hbd-font-family-accent);  font-size: var(--hbd-font-size-h4); letter-spacing: var(--hbd-letter-spacing-display); line-height: var(--hbd-line-height-display); }
  code, pre, kbd { font-family: var(--hbd-font-family-mono); }
  :focus { outline: none; }
  :focus-visible {
    outline: var(--hbd-border-width-thin) solid var(--hbd-color-focus-ring-outline);
    outline-offset: var(--hbd-focus-offset);
    border-radius: var(--hbd-radius-sm);
  }
  .hbd-sr-only {
    position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px;
    overflow: hidden; clip: rect(0 0 0 0); white-space: nowrap; border: 0;
  }
}

@media (forced-colors: active) {
  :focus-visible { outline: var(--hbd-border-width-thin) solid ButtonText; outline-offset: var(--hbd-focus-offset); }
}

@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
    scroll-behavior: auto !important;
  }
}`;

// Fold every de-shadowed component stylesheet (alpha order keeps shared definers
// — button/input/menu/skeleton/avatar — before their consumers).
const compDir = `${REG}/registry/new-york/styles/components`;
const compFiles = readdirSync(compDir)
  .filter((f) => f.endsWith(".css"))
  .sort();
let components = `

/* ════════════════════════════════════════════════════════════════════════════
 * HBD COMPONENT STYLES — ${compFiles.length} de-shadowed stylesheets, folded into
 * the theme so one globals import loads every component's styles (Next-safe).
 * Unlayered, after @layer base, to preserve the original ds/index.css cascade.
 * ════════════════════════════════════════════════════════════════════════════ */
`;
for (const f of compFiles) {
  components += `\n/* ──────── ${f} ──────── */\n` + read(join(compDir, f)) + "\n";
}

const out =
  [header, tokens, light, dark, hc, aliases, shadowBump, themeBlock, base].join("\n\n") +
  components +
  "\n";
const dest = `${REG}/app/globals.css`;
writeFileSync(dest, out);
console.log(
  `wrote ${dest}: ${statSync(dest).size} bytes, ${compFiles.length} component stylesheets folded in`,
);
